# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11af607f9234c51f57a173eed7a6d1e7f87df0f99159f4043264808dcda722ff258c5b73b698f20be916849a8ea01e11a9d78c5a607c42eca307fa539a71dc5b

test:
  secret_key_base: 1247d7857e24888758ecd7b2819979bf44ab45b78dbe2fb57c6c50c3946ac4daff8d3f49cdf546971bcaafb289f695a1525499aa16780dc704322cb98007fbb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
